# shinyproxy
# FROM openanalytics/r-base
FROM openanalytics/r-ver:4.3.1
FROM rocker/shiny:latest

MAINTAINER Kevin Stachelek "kevin.stachelek@gmail.com"

RUN apt-get update && apt-get install --no-install-recommends -y \
    sudo \
    pandoc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libssl3 \
    libhdf5-dev \
    libboost-all-dev \
    libudunits2-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    librsvg2-dev \
    cmake \
    build-essential \
    libglpk40 \
    libbz2-dev \
    liblzma-dev \
    && rm -rf /var/lib/apt/lists/*
    
RUN apt-get update && apt-get install --no-install-recommends -y \
    tk-dev
   

# system library dependency for the euler app
RUN apt-get update && apt-get install -y \
    libmpfr-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e 'install.packages("remotes")'
RUN R -e 'install.packages("sf")'
RUN R -e "install.packages('igraph', dependencies = T, repos='https://cloud.r-project.org/')"
RUN R -e 'install.packages("BiocManager")'
RUN R -e 'BiocManager::install(version = "3.21")'
RUN R -e 'BiocManager::install(c("batchelor", "DelayedArray", "DelayedMatrixStats", "limma", "S4Vectors", "SingleCellExperiment", "SummarizedExperiment"))'
RUN R -e 'BiocManager::install("pcaMethods")'
RUN R -e 'BiocManager::install("Biobase")'
RUN R -e 'BiocManager::install("tximport")'
RUN R -e 'BiocManager::install("annotables")'
RUN R -e 'BiocManager::install("genefilter")'
RUN R -e 'BiocManager::install("wiggleplotr")'
RUN R -e 'BiocManager::install("ensembldb")'
ARG GITHUB_PAT
ENV GITHUB_PAT=$GITHUB_PAT
RUN R -e 'install.packages("Seurat")'
RUN R -e 'install.packages("clustree", dependencies=TRUE)'
RUN R -e 'install.packages("ggpubr", dependencies=TRUE)'
RUN R -e 'remotes::install_github("velocyto-team/velocyto.R")'
RUN R -e 'remotes::install_github("cole-trapnell-lab/monocle3")'

# install dependencies of the euler app
RUN R -e "install.packages(c('shiny', 'rmarkdown'), repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('Rmpfr', repos='https://cloud.r-project.org/')"

RUN R -e 'install.packages("R.utils", repos="https://cloud.r-project.org/")'
RUN R -e 'remotes::install_github("satijalab/seurat-wrappers")'

RUN apt-get update && apt-get install -y python3 python3-pip
RUN apt-get update && apt-get install -y python3 python3-matplotlib

RUN R -e 'install.packages("tidyverse")'
RUN R -e 'BiocManager::install("InteractiveComplexHeatmap")'
RUN R -e 'BiocManager::install("plyranges")'

COPY Rprofile.site /usr/local/lib/R/etc/

RUN R -e 'install.packages("RSQLite")'
RUN R -e 'BiocManager::install("EnsDb.Hsapiens.v86")'
RUN R -e 'BiocManager::install("velociraptor")'
RUN R -e 'remotes::install_github("cobriniklab/seurattools")'
RUN R -e 'install.packages("formattable")'

RUN rm -rf /srv/shiny-server/*
WORKDIR /srv/shiny-server/
RUN mkdir /root/seuratApp
# Custom cache invalidation
ARG CACHEBUST
COPY ./dockerapp/app.R ./seuratApp/app.R
COPY ./euler ./euler
COPY ./index.html ./index.html